export class Dfsedit {
    publicationId: number;
    doi: string | null;
    title: string;
    levelId: number;
    level: string;
    volume: string | null;
    issno: string | null;
    bPage: string | null;
    ePage: string | null;
    acceptedDate: string;
    onlineDate: string;
    printDate: string | null;
    publishedDate: string | null;
    crossrefDate: string | null;
    conferenceName: string | null;
    webLink: string | null;
    publisherId: number;
    publisherName: string;
    publicationSourceId: number;
    publicationSourceName: string;
    articleTypeId: number;
    articleTypeName: string;
    year:string;
    pissn: string;
    eissn: string;
    pisbn: string | null;
    eisbn: string | null;
    abstract: string | null;
    authors: string | null;
    authorAddress: string | null;
    technologyArea: string | null;
    // sourceName: null;
    isPubSrcCorrect: number;
    pubSrcRemark: string;
    pubSrcArticleTypeId:string | null;
    pubSrcArticleTypeName:string | null;
    srcUniversityId: number;
}
